version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.6.8  # primary container for the build job
    steps:
      - checkout
      - run:
          name: "Install Pipenv"
          command: "sudo pip install --user pipenv"
      - run: 
          name: "Install Needed Dependencies"
          command: "pipenv install"
      - run:
          name: "Run Pytest Examples"
          command: "pipenv run pytest-vdc-us"
      - run:
          name: "Run Robot Examples"
          command: "pipenv run robot-vdc-us"

